### ISSUE TITLE
Support mail missing

### ISSUE THREAD

**Issue by flexwie** [Wouter01/MediaMate-Releases#1]
**Describe the bug**
The error message for an expired/fully used license key is missing the mail address:

**To Reproduce**
1. Open settings
2. Go to "More"
3. Enter expired/full license key

**Screenshots**
![image](https://user-images.githubusercontent.com/1215778/182095346-ce84049a-fcd1-40b9-8cd9-3394dbf6113c.png)

**Please complete the following information:**
 - OS: Monterey 12.4
 - Device: MBP 2021
 - Version: [v1.0_606](https://github.com/Wouter01/MediaMate-Releases/releases/tag/v1.0_606)

**Comment by Wouter01** [comment]
This is solved in v1.0_54.
