### ISSUE TITLE
Cannot press through the volume/brightness HUD

### ISSUE THREAD

**Issue by ghost** [Wouter01/MediaMate-Releases#10]
**Describe the bug**
Cannot press through the HUD

**To Reproduce**
1. Make sure you have volume (or brightness or keyboard brightness) HUD turned ON
2. Try to click through the HUD

**Expected behavior**
I expect to be able to click through the HUD like with the original macOS HUD

**Please complete the following information:**
 - OS: macOS Ventura beta 13 (22A5321d)
 - Device Macbook pro 2018 15in
 - Version 1.3 build 104

**Comment by Wouter01** [comment]
After consideration, I've decided this works as intended, as the hud can be dragged with the mouse
