### ISSUE TITLE
UI is not centered if Dock is moved to the side

### ISSUE THREAD

**Issue by zandrro** [Wouter01/MediaMate-Releases#12]
**Describe the bug**
If the Dock is not on the bottom, MediaMate will adjust its position, making all of its UI elements off-centered relative to the screen. This is especially noticeable when notch-style Now Playing is enabled, as the UI will shrink into a notch cutout that isn't hidden under the notch.

**To Reproduce**
1. Move your Dock to the left or right
2. Activate MediaMate in any way

**Expected behavior**
MediaMate should ignore the position of the Dock when calculating the screen's center.

**Screenshots**
https://github.com/Wouter01/MediaMate-Releases/assets/63067831/e8d18e70-a49c-476d-b4ff-94c5b3cf12c9

While my physical notch isn't visible in the screen recording, you can see that MediaMate's fake notch isn't in the center of the screen. In real life, this makes the notch temporarily look wider.

**Please complete the following information:**
 - OS: Ventura 13.5.1
 - Device M2 MacBook Air
 - Version 2.2.3 build 194

**Comment by Wouter01** [comment]
Thank you for the bug report! This will be fixed in the upcoming version, which should be coming soon.

**Comment by Wouter01** [comment]
Resolved in version 2.2.4
