### ISSUE TITLE
Option to set which display volume and brightness controls are shown

### ISSUE THREAD

**Issue by TechSupportz** [Wouter01/MediaMate-Releases#13]
First of all, I'm loving this app it really feels like it was made by apple themselves. However there is one feature that I think would be a nice addition. 

What if we are able to pick which monitor where the brightness and audio control popups are displayed like we can lock the now playing to the display with a notch. I use 2 monitors and I would like my audio and brightness bars to only display on my main laptop display rather than where my current active window is.

Once again, really love the app. Looking forward to the future updates!

**Comment by Wouter01** [comment]
Thank you for the feature request. I'll take it into consideration!

**Comment by Wouter01** [comment]
Version 3.1 has added the ability to further customize where HUDs are shown.
