### ISSUE TITLE
Brightness HUD support for 3rd party brightness control software

### ISSUE THREAD

**Issue by juliamertz** [Wouter01/MediaMate-Releases#14]
Hi, i've been using MediaMate for a while now and it's been working great!

The only issue i've had with it is that i use 3rd party software to control my brightness on both my built-in screen and my external monitor and keep them synchronised, but MediaMate does not show the brightness HUD for this. 

Is there any way to have MediaMate pick up on brightness changes made with external software, or is there a program that is already supported?

I have currently tried it with MonitorControl, Lunar and BetterDisplay. these all didn't work as expected.

- OS: macOS Ventura 13.3
- Device: MacBook Pro 13-inch M2 2022
- Version 2.3.0 build 197

**Comment by Wouter01** [comment]
Hi, compatibility with most of these apps is limited as MediaMate cannot know when these apps change the brightness of external displays. However, MediaMate can work with Lunar. You can enable this mode by going into settings -> advanced -> event controller and set brightness to "Lunar"

**Comment by juliamertz** [comment]
Ah perfect, this was exactly what i was looking for.
I completely missed this option when looking through the settings. Thank you very much!
