### ISSUE TITLE
Brightness HUD placement is off after connecting to external display.

### ISSUE THREAD

**Issue by juliamertz** [Wouter01/MediaMate-Releases#15]
**Describe the bug**
The brightness HUD placement get's thrown off after connecting an external display. even though the volume HUD is placed correctly.

**To Reproduce**
1. Make sure MediaMate is running
2. Enable brightness HUD (placement right in my case)
3. Connect device to an external display
4. Change brightness level while focus is on external display

**Expected behavior**
HUD Should be placed on the right.

**Screenshots**
![gif showing wrongly placed brightness hud](https://i.imgur.com/FB0oLgS.gif)

**Please complete the following information:**
 - OS: Ventura 13.3
 - Version 2.3.0 build 197
 - Device: Macbook Pro 13-inch 2022 M2 (1440x900)
 - External display: 2560x1440

**Comment by Wouter01** [comment]
Thank you for the bug report. Does this issue only occur when the HUD is placed sideways? (So at the left or the right)

**Comment by juliamertz** [comment]
It seems to occur in all positions. Even when I change the placement it persists until I quit and reopen.

**Comment by Wouter01** [comment]
> It seems to occur in all positions. Even when I change the placement it persists until I quit and reopen.

Thank you for the quick response! I'll investigate and let you know once I find a solution

**Comment by Wouter01** [comment]
Apologies for the late response, I was on a holiday. I'm investigating the issue and I think I've found the issue. Just to check, have you enabled the Lunar support mode?

**Comment by juliamertz** [comment]
I did have it enabled at the time i opened this issue, but after having some troubles with it constantly resetting my color space i uninstalled it. I'll check tonight if this problem still persists.

**Comment by juliamertz** [comment]
I'm unable to reproduce the bug without lunar running, this was most likely causing the issue.

**Comment by Wouter01** [comment]
Thank you for letting me know! A fix has been applied which should fix the issue in Lunar-compatibility mode in the next update. Note that there's another Lunar-related issue when connecting a new monitor, which will be addressed in a future Lunar update.

**Comment by Wouter01** [comment]
The update containing the fix has been released. If your issue has been resolved you can close this :)

**Comment by juliamertz** [comment]
Everything seems to work as intended now! Thanks a lot :)
