### ISSUE TITLE
Unable to control brightness when connected to external monitor with cable which doesn't support DDC

### ISSUE THREAD

**Issue by samwzlim** [Wouter01/MediaMate-Releases#17]
**Describe the bug**
Unable to control brightness when connected to external monitor with cable which doesn't support DDC when Event Controller for Brightness is set to MediaMate. Works perfectly when Event Controller for Brightness is set to System (but no overlay shows) or external monitor is not connected.

**To Reproduce**
1. Make sure machine is on macOS Sonoma
2. Connect to external monitor (using cable which doesn't support DDC)
3. Changing brightness will bring up overlay but doesn't actually change brightness

**Expected behavior**
Brightness should be changed 

**Please complete the following information:**
 - OS: Sonoma Release Candidate
 - Device: M2 MacBook Air
 - Version 2.3.0 build 197

**Comment by Wouter01** [comment]
Thank you for the bug report. Are you referring to setting the brightness of the internal display, or the external display? I’m assuming you know that it won’t work for a monitor with DDC support, but it should work for the internal display. I’ll look further into this issue and will try to solve it as soon as possible.

**Comment by samwzlim** [comment]
It doesn't work for both displays, as the external display doesn't support DDC and for some reason it affects the internal display as well.

**Comment by Wouter01** [comment]
This issue has been addressed and a fix will be included in the next update

**Comment by Wouter01** [comment]
The update containing the fix has been released. If your issue has been resolved you can close this :)
