### ISSUE TITLE
Default Volume/Brightness/Keyboard UI not being suppressed

### ISSUE THREAD

**Issue by omarsonmarz** [Wouter01/MediaMate-Releases#18]
**Describe the bug**
Default Volume/Brightness/Keyboard UI shows after waking from sleep

**To Reproduce**
1. Set any HUD
2. Put computer to sleep
3. Press function keys/scrub the Touch Bar (Touch Bar in my case)

**Expected behavior**
Default Volume/Brightness/Keyboard UI should not show up

**Screenshots**
![Screenshot 2023-09-21 at 9 30 30 AM](https://github.com/Wouter01/MediaMate-Releases/assets/74555681/a82061e8-3669-4c5c-9095-4e21c0884d9a)

**Please complete the following information:**
 - OS: Sonoma (14 Public Beta 6)
 - Device M1 Macbook Pro 13' (Touch Bar)
 - Version 2.3.0 build 197

**In case of a keyboard-related issue, please specify the used keyboard**:
- Layout: US QWERTY
- Internal
- Touch Bar

**Additional context**

EDIT: Default UI has started to pop up randomly when idle, pops up every 2 minutes or so when not touching either the keyboard or the trackpad
EDIT 2 (sorry): Default UI is popping up pretty much whenever it wants, and sometimes stays on the screen forever. Have had to kill OSDUI helper in activity monitor when this happens.

**Comment by Wouter01** [comment]
Thank you for the extensive bug report. Support for the touchbar should work, but I'm not able to test a lot as I don't have access to a touchbar macbook. That said, the issues you're seeing. Does this issue always occur or sometimes?

As a sidenote, MediaMate controls the OSDUI Helper process too, and puts it in a state where it should not show a HUD. Manually killing the process makes MediaMate temporarily lose 'control' of the process and is likely the cause of the hud staying on the screen forever. Could you try rebooting your mac, not kill osdui, and report which problems you see then?

**Comment by omarsonmarz** [comment]
1. The issue sometimes it happens after sleep, and other times it happens after long use of the computer.
2. I've tried rebooting as you've said, and the problem still persists.

A bit of a suggestion as well: As I used SlimHUD (another HUD replacement app) on my old MacBook before I found MediaMate, I tried looking at SlimHUD's GitHub repo to see if AlexPerathoner had the same problem, seems like they have: [SlimHUD](https://github.com/AlexPerathoner/SlimHUD/issues/134). 
I don't think he's found a solution to the problem either, and it's seen on non-touchbar MacBooks as well, which is weird. Not sure if your solution to removing the OSDUIhelper is the same as his though.

**Comment by omarsonmarz** [comment]
OSDUI popped up again, except this time it seems that it has frozen. As seen in the screenshot the MediaMate volume is correct, while OSDUI has frozen and is stuck on a lower volume.
![Screenshot 2023-09-26 at 12 42 04 PM](https://github.com/Wouter01/MediaMate-Releases/assets/74555681/f28cba37-04c4-4389-9881-75e529a3df2d)

**Comment by omarsonmarz** [comment]
Messing around with the settings, I found that setting the event controller to "MediaMate" instead of "System" made the problem go away. Will probably just stick to MediaMate's controller as it's pretty much the same thing as the system controller when using the Touch Bar.

**Comment by Wouter01** [comment]
> Messing around with the settings, I found that setting the event controller to "MediaMate" instead of "System" made the problem go away. Will probably just stick to MediaMate's controller as it's pretty much the same thing as the system controller when using the Touch Bar.

I'm actually surprised that works, as the "MediaMate" option isn't compatible with the touch bar volume and brightness sliders. Unless you're using the buttons instead of the sliders, then it'll work as intended
