### ISSUE TITLE
Now playing notch HUD is unable to be closed if launched from the "Expanded" now playing shortcut

### ISSUE THREAD

**Issue by Bryceshaw06** [Wouter01/MediaMate-Releases#19]
Sorry, this one's a little hard to describe. If you have a shortcut set to Show/Hide the "Expanded" Now Playing HUD (Classic Mode only!!!) but the notched mode is enabled, then you're unable to close out the HUD until you use the shortcut again. "Workaround" is to use your shortcut on the "Show/Hide Now Playing HUD" section instead of "Show/Hide Expanded Now Playing HUD". Just a bit of unexpected behavior, nothing crazy. Here's a video of me trying to show it: https://share.cleanshot.com/5WT20SFD

 - M1 Macbook Air
 - Sonoma (Latest)
 - Command used was Ctrl+M if it makes a difference

**Comment by Wouter01** [comment]
Thank you for the report! This is actually intended behavior, as I got some requests to make it possible to leave the HUD visible until the key was pressed again. It's not documented anywhere in the app, as it'll likely get replaced once I create the "expanded" version of the notch-style HUD.

**Comment by Bryceshaw06** [comment]
Gotcha! That makes sense then, I just had my command mapped to the expanded mode because I was messing around to see which one I liked more. Also, I assume you're aware of this, but the Now Playing app logo doesn't come up on the notched mode, while it does on the classic mode (If there's no artwork). You can see that on my video above. It would be nice to see that functionality fixed/added when the expanded notched HUD gets finished. Thanks again for the quick replies and helpful support!

**Comment by Wouter01** [comment]
> Gotcha! That makes sense then, I just had my command mapped to the expanded mode because I was messing around to see which one I liked more. Also, I assume you're aware of this, but the Now Playing app logo doesn't come up on the notched mode, while it does on the classic mode (If there's no artwork). You can see that on my video above. It would be nice to see that functionality fixed/added when the expanded notched HUD gets finished. Thanks again for the quick replies and helpful support!

I actually forgot about that! I'll add it in the next update
