### ISSUE TITLE
Incorrectly detects Touchbar on M2 Max MBP

### ISSUE THREAD

**Issue by kaygdotorg** [Wouter01/MediaMate-Releases#21]
**Describe the bug**
The app incorrectly detects a touchbar on my M2 Max 16 inch MBP. 

**To Reproduce**
![CleanShot 2023-11-15 at 12 52 49@2x](https://github.com/Wouter01/MediaMate-Releases/assets/30401343/5e139647-54c7-481d-9d18-246831cf7809)

**Expected behavior**
No touchbar message should popup. 

**Screenshots**

**Please complete the following information:**
 - OS: MacOS Sonoma 14.1
 - Device: 16 inch M2 Max MBP
 - Version 2.4.1
 
**In case of a keyboard-related issue, please specify the used keyboard**:
- Layout: [e.g. ANSI QWERTY]
- Internal/External (+ brand/model)
- touchbar/non-touchbar

**Additional context**
- Laptop lid closed
- Connected to an external monitor
- Keyboard used is a ergonomic split keyboard: fifi

**Comment by Wouter01** [comment]
Thank you for the bug report. Have you been using the touchbar simulator in Xcode by any chance?

**Comment by kaygdotorg** [comment]
Nope, I just have Xcode installed and have never used it.

**Comment by Wouter01** [comment]
That's weird. To determine if your mac has a touchbar, MediaMate will check if the TouchBarServer process is running or not. It is possible that something else triggered the launch of this process, but it shouldn't be running by default.

One other possibility is that you used Sidecar, and had the "Show touch bar" option enabled. This will launch the TouchBarServer process too, and it will keep running unless you reboot.

MediaMate will only show this dialog once, so you shouldn't see it anymore now.

**Comment by kaygdotorg** [comment]
Hey, i can check if the server process is running or not when I'm home but I don't have an ipad to use Sidecar.

18-Nov-2023 18:21:15 Wouter Hennen ***@***.***>:

**Comment by kaygdotorg** [comment]
You're right, the touchbarserver process is running: 
![CleanShot 2023-11-19 at 06 32 03@2x](https://github.com/Wouter01/MediaMate-Releases/assets/30401343/330e914b-34b8-4917-93e7-100db14f89f6)

Since Macs with touchbar are no longer updated, can you not maintain a list of Macs that have touchbars for sure and have the app crosscheck if it's installed on one of those macs?

**Comment by Wouter01** [comment]
Yes, that's now a possibility

**Comment by Wouter01** [comment]
A new update has been released which fixed this issue
