### ISSUE TITLE
Songs with some type of artwork crash the app

### ISSUE THREAD

**Issue by macsen0** [Wouter01/MediaMate-Releases#22]
**Describe the bug**
Some songs crash the app. Managed to figure is the artwork, since some of these songs are mine and uploaded a long time ago. I'm not sure what is the problem with the image, but it crashes the app.

**To Reproduce**
1. Play a song with the artwork that crashes the app.
2. The App crashes.

**Expected behavior**
Obviously, it should not crash, but if the thumbnails are the culprits, the app should ignore them.

**Please complete the following information:**
 — OS: Sonoma 14.2.1
 — MacBook Pro M1 Pro

**Additional context**
It's just weird. And it would be very impractical to check all of my songs to see what crashes the app and what does not. Probably check the thumbnail implementation?

**Comment by Wouter01** [comment]
Thank you for the bug report. Would it be possible to attach the file / artwork you're experiencing issues with?

**Comment by macsen0** [comment]
￼

That one does it… copied pasted it from Music (seems like there are the ancient CD rips I did a long time ago)

If you need, I can send you a song too



Rick Robles
http://rickrobles.myportfolio.com

**Comment by Wouter01** [comment]
Unfortunately I can't see any image / file in your reply. Could you try sending the artwork / music via email to media.mate@icloud.com ? Thank you!

**Comment by Wouter01** [comment]
Thank you for the mail. I've had a look and the crash happens in Apple's ScriptingBridge framework. This issue also affects other apps using the same framework. The next version of the app does not use this framework anymore and therefore does not have this issue. So I will keep this issue open for now, but once that version has been released I will close it.

**Comment by macsen0** [comment]
Thank you very much… I’ll be waiting that next version.

Keep the amazing work!

Rick


Rick Robles
http://rickrobles.myportfolio.com

**Comment by Wouter01** [comment]
A new version has been released which fixes this issue.
