### ISSUE TITLE
Feature request: Dynamic Island style for displays without notches

### ISSUE THREAD

**Issue by xezrunner** [Wouter01/MediaMate-Releases#24]
A Dynamic Island oval-shaped overlay with the same animations would look nice on displays that do not have a notch cutout (pre-notch MacBooks, external displays).

It could act like it does on recordings, where it fades in and out as it appears/disappears on the screen:

https://github.com/Wouter01/MediaMate-Releases/assets/8061077/b988821c-e0bd-4e1d-9144-e80470179ecc

**Comment by Wouter01** [comment]
Thank you for the feature request. I will take it into account!

**Comment by Kastakin** [comment]
+1 for this! I actually expected this to already be in the package!

it would be nice to have the possibility to click/hover to show in the middle of a not-notch-equipped screen! 

Notch dropdown would look amazing on external displays as well for consistency. The demo from settings is already really good!

![image](https://github.com/Wouter01/MediaMate-Releases/assets/15200602/912895a8-5b30-42e4-8f12-4818202339a2)

**Comment by Wouter01** [comment]
After consideration, I have decided to not add this feature. The menu bar on non-notched displays is too small to put this kind of stuff into, and extending it below the menu bar does not look good. When (if) Apple decides to remove the notch from their displays, and keep the menubar height as tall as it is at the moment, this may be revisited.

**Comment by xezrunner** [comment]
> The menu bar on non-notched displays is too small to put this kind of stuff into, and extending it below the menu bar does not look good.

That's totally understandable on notched displays, and I assume it wouldn't be very fair to include it just for displays without cutouts.

Just for reference, here's a concept of what I imagined it would look like on a display without a notch. It looks fine there.

Perhaps having it below the dock would make sense if it were included as an option on notched devices? Would space it out and not make it look like a double-cutout.

https://github.com/Wouter01/MediaMate-Releases/assets/8061077/237b4f53-5003-4cd5-bbc6-70340132aeee

**Comment by Wouter01** [comment]
Thank you for the video. I still think this would not work well in practice, at least not for the use cases of MediaMate
