### ISSUE TITLE
Feature request: Multiple artists in Now Playing HUD

### ISSUE THREAD

**Issue by byung806** [Wouter01/MediaMate-Releases#28]
**Describe the bug**
When playing songs with multiple artists, only the first one shows.

**To Reproduce**
1. Play a song with 2+ artists (ex: A Night to Remember by beebadoobee and Laufey)
2. See only the first artist is shown in Now Playing

**Expected behavior**
Both artists should show under the song name

**Screenshots**
![unknown](https://github.com/Wouter01/MediaMate-Releases/assets/87292945/28df3444-d1d4-4db4-ad45-d1c57fc46572)

If spacing doesn't work, I would understand if the app stays the way it is now
Thank you for your time reading! I promise I'm done posting for today 😆

**Comment by Wouter01** [comment]
Thank you for the bug report. What music service are you using to play the song? I'm pretty certain this is a limitation where the service will only send the first artist, and not the second. I will have a look to see if I can fix this, but I don't think it's possible

**Comment by byung806** [comment]
I'm using Spotify to play the song.

That's alright if it's a limitation with the service - thank you for trying anyways.
