### ISSUE TITLE
Keyboard brightness keys are not captured when using BetterDisplay event mode

### ISSUE THREAD

**Issue by x-magic** [Wouter01/MediaMate-Releases#29]
**Describe the bug**
The keyboard brightness shortcuts (control + brightness up/down) won't change keyboard brightness when using BetterDisplay event mode on Macs without dedicated keyboard brightness function key. 

I kind of know why... Probably because MediaMate is waiting for BetterDisplay to call events, but BetterDisplay doesn't really manage keyboard brightness adjustment shortcuts. 

**To Reproduce**
1. When MediaMate event mode is either `Keyboard` or `System`, `control + brightness up/down` would adjust keyboard brightness and HUD shown as normal
2. Set MediaMate event mode to Better Display
3. Change keyboard brightness using shortcut key as mentioned above, this would change the screen brightness instead of keyboard brightness

**Expected behavior**
When shortcut key triggered, keyboard brightness should be adjusted instead of screen brightness. 

**Screenshots**
N/A

**Please complete the following information:**
 - OS: macOS 14.2.1 (23C71)
 - Device: MacBook Air M2 2022
 - Version: 3.0.5 build 246

**In case of a keyboard-related issue, please specify the used keyboard**:
- Layout: US/ANSI QWERTY
- MacBook built-in keyboard
- Non-touchbar

**Additional context**
N/A

**Comment by Wouter01** [comment]
Thank you for the bug report. This issue is not caused by BetterDisplay, but by MediaMate only supporting keyboard brightness in "Keyboard" mode, because otherwise the custom shortcut cannot work. This isn't clear in settings. In a future update (probably 3.1), a new option will be added to create custom shortcuts for keyboard brightness up / down, which should work fine in combination with BetterDisplay

**Comment by x-magic** [comment]
I wrote an issue in BetterDisplay and @waydabber suggested that BD does have options to set up shortcuts for keyboard brightness (I didn't see that coming!). And those shortcuts seem to trigger keyboard brightness events in MM as well so I can see the HUD showing up. 

See https://github.com/waydabber/BetterDisplay/discussions/2733#discussioncomment-8718956

Just that shortcuts in BD can't have media keys involved so control + brightness up/down won't work. 

Well this is good enough for me for now. Cheers
