### ISSUE TITLE
Media Preview shows multiple times

### ISSUE THREAD

**Issue by flexwie** [Wouter01/MediaMate-Releases#3]
**Describe the bug**
The preview of what's currently playing is sometimes showing up multiple times even if the playing media is not interacted with.

**To Reproduce**
1. Open a video on YouTube
2. Move cursor in and out of the video

**Screen Recording**
[Recording](https://www.veed.io/view/0bc69bb9-852f-4789-9975-7d58a6acd5e1?sharingWidget=true)

**Expected behavior**
Preview shows once at the start of the video.

**Please complete the following information:**
 - OS: Monterey 12.4
 - Device M1 Pro MBP 2021
 - Version v1.0_53

**Comment by Wouter01** [comment]
Thanks for the feedback! Does this bug happen frequently?
I noticed that bug some time ago, although it doesn't seem to happen a lot to me (on Safari). Are you by any chance using an adblocker? (I have some reasons to think that is causing the issue).

**Comment by Wouter01** [comment]
A possible fix has been released in the newest version of the app. Can you give it another shot? Thanks!
