### ISSUE TITLE
Notch HUD flying between screens when using multiple monitors

### ISSUE THREAD

**Issue by x-magic** [Wouter01/MediaMate-Releases#30]
**Describe the bug**
The Notch HUD in beta is flying between screens when cursor moved between screens while triggering brightness/volume events. 

**To Reproduce**
0. Connect an external monitor
1. Swtich HUD type to Notch (beta) in MediaMate
2. Trigger any event (adjust volume, brightness) so the HUD shows up
4. Move the cursor to another screen, and wait until the HUD disappear
5. Either immediately or wait a bit after the HUD disappear on the other display, trigger any event on the current active display, and the hud is flying!

**Expected behavior**
The notch should just show up on the focused screen instead of flying into presence

**Screenshots**
See video: https://github.com/Wouter01/MediaMate-Releases/assets/3180639/c9c37452-b6b8-4b0d-a37d-2ee22e7f12d3

**Please complete the following information:**
- OS: macOS 14.2.1 (23C71)
- Device: MacBook Air M2 2022
- Version: 3.0.5 build 246

**In case of a keyboard-related issue, please specify the used keyboard**:
- Layout: US/ANSI QWERTY
- MacBook built-in keyboard
- Non-touchbar

**Additional context**
Give Notch HUD some adderall🙃

**Comment by Wouter01** [comment]
Thank you for the bug report. This is a known issue which will be fixed in a future update. (its on my priority list)

Stay tuned!

**Comment by Wouter01** [comment]
The latest update should have fixed this issue. Can you check and close the issue?

**Comment by x-magic** [comment]
> The latest update should have fixed this issue. Can you check and close the issue?

Works like a charm 👍
