### ISSUE TITLE
Feature Request: Option for the meter to be at the same height of the native macOS meter (Or ability to configure height)

### ISSUE THREAD

**Issue by AviKav** [Wouter01/MediaMate-Releases#31]
I'd like if the non-notch HUDs weren't so close to the bottom of the screen. It might be fine if if I were using an external monitor, but with a laptop display its too hard for me to see.

**Comment by Wouter01** [comment]
You can increase the distance from the screen edge by going into MediaMate settings -> advanced -> compact HUD inset. Does this solve your issue?

**Comment by AviKav** [comment]
Oh! I'm an idiot. I must have had the style set to Notch.

**Comment by AviKav** [comment]
Okay, turns out the max of 100 is too low for me

**Comment by Wouter01** [comment]
Where exactly would you like to place the HUD? Have you tried the "center" placement option? That one will place the HUD in a similar spot like the native one

**Comment by AviKav** [comment]
...I completely missed that option
