### ISSUE TITLE
Feature request: no media change display on DND

### ISSUE THREAD

**Issue by byung806** [Wouter01/MediaMate-Releases#33]
Normally, I love to have the music preview pop up whenever the current song ends and it autoplays to the next one. However, I would love if there was an option to disable these automatic now playing pop ups while Do not Disturb is active as a focus.

**Comment by Wouter01** [comment]
MediaMate supports focus filters, which should have the behavior you expect. If you go into the focus filter settings, you should be able to add a focus filter for MediaMate

**Comment by byung806** [comment]
I missed that. Thank you!
