### ISSUE TITLE
Volume & Slider not appear in notch

### ISSUE THREAD

**Issue by FelixKLG** [Wouter01/MediaMate-Releases#35]
**Describe the bug**
After updating MediaMade (a couple of versions) I find that when I'm adjusting my volume it uses the normal pop-up and doesn't integrate with the notch on my screen. The notch works for media playing however volume and brightness are now relegated off to some modal pop-up.

**To Reproduce**
1. Backdate a couple versions? Configure everything to use the notch
2. Update to latest
3. Play/Pause media and is in notch
4. Adjust vol/brightness and see non-notch pop-up

**Expected behavior**
The volume and brightness should stack in the notch like it did.

**Screenshots**

![CleanShot 2024-02-15 at 10 10 30@2x](https://github.com/Wouter01/MediaMate-Releases/assets/44820580/ade652ff-f7cb-4d79-984c-e7e67efad540)
![CleanShot 2024-02-15 at 10 12 39@2x](https://github.com/Wouter01/MediaMate-Releases/assets/44820580/e75b9ba0-b62c-418f-94fc-2d4b59795b02)

**Please complete the following information:**
 - OS: Sonoma 14.3.1
 - Device M1 Macbook Pro
 - Version 3.1.1 build 257

**Additional context**
I was out of data by a couple versions before I updated MediaMate last night, only realised this morning.

**Comment by FelixKLG** [comment]
Placement options for Now Playing are greyed out 
![CleanShot 2024-02-15 at 10 16 51@2x](https://github.com/Wouter01/MediaMate-Releases/assets/44820580/7afc4e93-98c8-467c-8c30-33ebbc8b8e1f)

For vol and the rest there's no notch option.
![CleanShot 2024-02-15 at 10 17 26@2x](https://github.com/Wouter01/MediaMate-Releases/assets/44820580/4439db90-455e-4e62-8ac0-fc5b97ee0a29)

**Comment by Wouter01** [comment]
Hi,

You can change the style of the system HUDs back to "notch" by selecting the "styles" tab in the sidebar.
When updating the app, some migrations need to be applied to ensure the old settings are correctly migrated to the new ones. I might've missed something there.

**Comment by Wouter01** [comment]
A new update has been released which fixes the migration issue. However, the fix only applies for users who hadn't upgraded to 3.1.0 yet.
