### ISSUE TITLE
Feature request : Is there able to use mediamate to push app notification like telegrame or whatsapp

### ISSUE THREAD

**Issue by xbunax** [Wouter01/MediaMate-Releases#36]
Is there able to push notification with mediamate like iPhone?
 
 + grep app notification and push with mediamate.
 +  It can use `lsappinfo` command to get this information.Like this 
<img width="1343" alt="image" src="https://github.com/Wouter01/MediaMate-Releases/assets/50800571/3672f31a-0ab2-4663-b086-712d50134ffd">

**Comment by Wouter01** [comment]
Hi,

Thank you for the feature request. The following code will only show the badge count. I have researched the possibility for notifications earlier, but it's not really doable and worth it.
