### ISSUE TITLE
BUG REPORT: Swipe on Brightness/Volume Sliders is Reversed

### ISSUE THREAD

**Issue by Bryceshaw06** [Wouter01/MediaMate-Releases#37]
Swiping on the Brightness/Volume Sliders is reversed. The issue started after the UI update for me.

Here's a video of it: https://cln.sh/kRtfN8kf

 - OS: Sonoma 14.2.1
 - Device M1 Macbook Air
 - Version Latest (3.1.2)

**Comment by Wouter01** [comment]
This issue will be fixed in the next update!

**Comment by Bryceshaw06** [comment]
Thanks, you’re the best!
