### ISSUE TITLE
two finger drag to change value not working

### ISSUE THREAD

**Issue by Awesomeplayer165** [Wouter01/MediaMate-Releases#38]
**Describe the bug**
The two finger drag to change value does not work for me. I have it enabled in styling > System HUD > iOS, but i can't drag with two fingers to change the value on my trackpad. Is there something wrong I am doing? Thanks!

**Comment by Wouter01** [comment]
This functionality has been fixed in the upcoming version of the app! (Will be released soon)

**Comment by Wouter01** [comment]
A new version has been released which fixes this issue.
