### ISSUE TITLE
Feature Request: Clock timer, alarm and show the connected device

### ISSUE THREAD

**Issue by frieza213** [Wouter01/MediaMate-Releases#40]
Hey there maybe add an option to show the progress with a progress bar around the notch like [noti](https://play.google.com/store/apps/details?id=com.gustavoas.noti&hl=en_US) or you can extend the notch just horizontally and not vertically so to have the timer and stopwatch show time left or time elapsed on right and app icon on left but optimized for mac's notch and show the name of bluetooth connected device at the time of pairing it would be a very nice addition in my opinion

**Comment by Wouter01** [comment]
Hi,
Thank you for the feature requests! What would you want to see "progress" of?
Ideas like a timer are nice, but can unfortunately not integrate with the system Clock app, which would require me to make a whole separate version of the feature, which I'm not planning to do. There's also the annoyance that not every display (e.g. external displays) has a notch, so displaying "info on the side" would get tricky in those situations

**Comment by frieza213** [comment]
so as you might have seen in the noti app whenever we do something like play media or start a timer there is a progress bar around the circular notch(in android) i think you should add such functionality but for apple's notch where depending on the progress it would show a line halfway through if the orogress is 50% 100% if it is fully done
Here is a screenshot to show what i mean:
![CleanShot 2024-02-25 at 12 16 15@2x](https://github.com/Wouter01/MediaMate-Releases/assets/121119257/c1c7f793-722b-4248-9f65-3781d7d8f462)

**Comment by frieza213** [comment]
i understand, but you can use this screenshot to implement another similar feature if you wish to do so

**Comment by frieza213** [comment]
also about the progress thing maybe you can add like download progress, how much of the song is left, or the progress of a currently playing video on like youtube or something

**Comment by frieza213** [comment]
also being able to see the bluetooth device's name at the time of pairing would be a really good feature too since my mac automatically pairs with my bluetooth device and i have two headphones so sometimes it gets confusing on which one is paired and i have to go check the control center instead if we had this feature i would directly be able to see the device name and act accorfingly

**Comment by Wouter01** [comment]
I might look into the bluetooth device idea, however, the others won't be coming
