### ISSUE TITLE
mediamate only shows up on internal display but not external 

### ISSUE THREAD

**Issue by avichou** [Wouter01/MediaMate-Releases#42]
the now playing notch only shows up on internal mba m1 display no matter what. it only shows up on external display if triggered within mediamate settings 

**Expected behavior**
now playing should show up on external monitor as well 

**Please complete the following information:**
 - OS: sonoma 14.3.1
 - Device [. M1 Macbook Air]
 - Version [3.1.2 build 258

**Comment by Wouter01** [comment]
What option have you set in the "Display Behvaior" settings? (mediamate settings -> general). Which event controller mode have you set? (mediamate settings -> general -> event controller mode). For the BetterDisplay & Lunar modes, MediaMate will show the HUD on the display the other app tells it should show, so it could be misconfigured there.

**Comment by avichou** [comment]
> What option have you set in the "Display Behvaior" settings? (mediamate settings -> general). Which event controller mode have you set? (mediamate settings -> general -> event controller mode). For the BetterDisplay & Lunar modes, MediaMate will show the HUD on the display the other app tells it should show, so it could be misconfigured there.

for "display behavior" I use "display with mouse" . (neither of the 3 options make a different as far as notch goes sadly)
 
 
 for event mode, i only use those two ,as both lunar and better display mean...more stuff running in the background right ?
 
 speaking of, how much ram does mediamate typically takes ? just curious
 
 
<img width="630" alt="image" src="https://github.com/Wouter01/MediaMate-Releases/assets/86660671/a3c35b8f-64c1-4e83-920b-c61a255a1fc7">
 

but anyway, for now "classic HUD" is much more complete than "notch HUD" so I settled on classic :)

**Comment by Wouter01** [comment]
Could you try restarting the app when your external display is connected? It could be that something goes wrong and mediamate doesn't know a new display is connected.

Lunar and BetterDisplay are two separate apps which both allow you to control the brightness of external third party displays. While both are relatively lightweight, they will indeed also run in the background.

As MediaMate is intended to constantly run, I have mostly focused on keeping the power usage as low as possible, but have also focused on keeping the memory usage minimal. Version 3 brought additional power savings, and the coming update will do too (in certain cases). 
As for memory usage, in normal day-to-day usage, the app should use around 25-50MBs of RAM. Opening the settings window will increase this with +/- 20 MB and this won't go down until the app has restarted (because of some reasons)

**Comment by avichou** [comment]
> Could you try restarting the app when your external display is connected? It could be that something goes wrong and mediamate doesn't know a new display is connected.
> 
> Lunar and BetterDisplay are two separate apps which both allow you to control the brightness of external third party displays. While both are relatively lightweight, they will indeed also run in the background.
> 
> As MediaMate is intended to constantly run, I have mostly focused on keeping the power usage as low as possible, but have also focused on keeping the memory usage minimal. Version 3 brought additional power savings, and the coming update will do too (in certain cases). As for memory usage, in normal day-to-day usage, the app should use around 25-50MBs of RAM. Opening the settings window will increase this with +/- 20 MB and this won't go down until the app has restarted (because of some reasons)

i restarted it but it's still the same (only with notch mode, not classic )

yeah I see. I use monitor control already. might look into those options instead hmm 


I see! thanks . yeah that's some really nice optimizing , good job :))

**Comment by Wouter01** [comment]
Oh, so when using classic mode, everything works as expected?

**Comment by avichou** [comment]
> Oh, so when using classic mode, everything works as expected?

yes, yes indeed. for now classic mode is far more advanced anyway so ig that's all good :)

the only thing where notch mode is superior is that you don't need to expand panel in order to scrub through the song . meanwhile classic mode small/default HUD doesnt have music control without clicking for big HUD 



<img width="462" alt="Capture d’écran 2024-02-28 à 15 40 36" src="https://github.com/Wouter01/MediaMate-Releases/assets/86660671/c04e6ede-e68a-4435-8fa8-93cabf4f60ac">
<img width="470" alt="Capture d’écran 2024-02-28 à 15 41 16" src="https://github.com/Wouter01/MediaMate-Releases/assets/86660671/f0b85fd1-8201-4981-8b42-156a68247e91">

**Comment by Wouter01** [comment]
Okay, thanks for the info. The classic style will eventually get redesigned so it follows the layout of the notch style more.

**Comment by avichou** [comment]
> Okay, thanks for the info. The classic style will eventually get redesigned so it follows the layout of the notch style more.

i see :) as long as it doesn't lose features i'm all for it ;p . classic has way more features than notch rn

**Comment by avichou** [comment]
hello again. any news on this issue ? as notch gets even better than classic now, I wanted to know if it could be fixed to be used on external display :)

**Comment by avichou** [comment]
https://github.com/Wouter01/MediaMate-Releases/assets/86660671/a3359014-8913-4e83-a776-6c98ae4873bf

**Comment by Wouter01** [comment]
Sorry, I forgot about this issue. I just rechecked and have absolutely no idea what could be causing this issue. I do have some things you could try out:

- Can you check if mediamate settings -> notch -> always show on screen with notch is disabled?
- Does the issue also occur when you only use the external display (laptop lid is closed)?
- Does the notch get shown on the external display if you set the System HUD style to "notch"?

**Comment by avichou** [comment]
> Sorry, I forgot about this issue. I just rechecked and have absolutely no idea what could be causing this issue. I do have some things you could try out:
> 
> * Can you check if mediamate settings -> notch -> always show on screen with notch is disabled?
> * Does the issue also occur when you only use the external display (laptop lid is closed)?
> * Does the notch get shown on the external display if you set the System HUD style to "notch"?

okay good call , so 

-"always show on screen with notch is disabled?" YES, thank you, disabling it shows it on external display 
-Does the issue also occur when you only use the external display (laptop lid is closed)? no,indeed, with laptop lip closed, the issue doesnt occur 
-setting to "notch" style makes no difference 


now i have another  issue though : i have the notch showing up when i click on menu bar icon. however , since last update, it doesnt work when i change the music (play/pause/next/previous) . 

actually since last update, going to next song and play/pause dont even work,even in classic mode . what the hell

**Comment by avichou** [comment]
> Sorry, I forgot about this issue. I just rechecked and have absolutely no idea what could be causing this issue. I do have some things you could try out:
> 
> * Can you check if mediamate settings -> notch -> always show on screen with notch is disabled?
> * Does the issue also occur when you only use the external display (laptop lid is closed)?
> * Does the notch get shown on the external display if you set the System HUD style to "notch"?

should I make another issue for this ? im pulling my hair off lol. why does everything break with me 

in TLDR, the new issue is ; notch/classic don't show when using media control (play/pause/next/prev)

**Comment by Wouter01** [comment]
Okay, glad that's solved now!
As for play/pause, the latest update did not change anything that could break it, so it should still work. Is it possible that you have multiple audio streams playing at the same time? The buttons displayed in the HUD function the same way as the keyboard buttons. Do the keyboard play/pause, next buttons work properly?

**Comment by avichou** [comment]
> Okay, glad that's solved now! As for play/pause, the latest update did not change anything that could break it, so it should still work. Is it possible that you have multiple audio streams playing at the same time? The buttons displayed in the HUD function the same way as the keyboard buttons. Do the keyboard play/pause, next buttons work properly?

sometimes it works , other times it doesnt. i really don't know what's wrong with me man

aand okay you know what I'm an idiot, forgive me man , i had disabled this option. i really need to see a good neurologist 

<img width="592" alt="image" src="https://github.com/Wouter01/MediaMate-Releases/assets/86660671/ce88f3fd-4b85-4b0e-8892-b319900bb32e">
