### ISSUE TITLE
make expanded window less persistent, and direct access to music controls 

### ISSUE THREAD

**Issue by avichou** [Wouter01/MediaMate-Releases#43]
not a bug, but I was wondering if It'd be possible to implement a way to get the "now playing" window to disappear , as soon as you click on anywhere on display....or simply when going into another app, instead of having the overlay being so PERSISTENT. 

for now it seems the only way to get back to work is by clicking on the widget itself, minimzing to the "smaller" now playing 

also, would it be possible to make controls (next/previous,15s) available directly, without having to click on artwork twice ?

only reason I still haven't bought it tbh. otherwise,it's just so perfect, such a beautiful piece of art, thank you :)

https://github.com/Wouter01/MediaMate-Releases/assets/86660671/025917ce-00db-449d-a79b-55407c778e62

**Comment by Wouter01** [comment]
Hi,

Adding the option to hide the hud when something is clicked doesn't make a lot of sense, as it would have too many false positives. If the HUD is popping up too much, you can limit when it should show in mediamate settings -> now playing -> reveal when. Personally, when the HUD is in the way, I like to use the keyboard shortcut to quickly hide it. When hovering over the HUD, a small "x" should also appear which you can click to dismiss the HUD.

**Comment by avichou** [comment]
> Hi,
> 
> Adding the option to hide the hud when something is clicked doesn't make a lot of sense, as it would have too many false positives. If the HUD is popping up too much, you can limit when it should show in mediamate settings -> now playing -> reveal when. Personally, when the HUD is in the way, I like to use the keyboard shortcut to quickly hide it. When hovering over the HUD, a small "x" should also appear which you can click to dismiss the HUD.

sorry what i mean is that clicking elsewhere (aka outside of the HUD, for example if you click on chrome browser to get back to working) , it dismisses the HUD popup. like what happens when you're in control center, and you click outside of it, it closes control center, and focuses on foreground app 

i'm not talking about the small HUD, im referring to the expanded panel. once i change the song, or go forward/rewind, once im done with it, i'd like to be able to close it by simply focusing on the app i was using ..before changing the song. do i make sense ?

**Comment by Wouter01** [comment]
That does indeed make more sense! I understand why you'd want that. I won't work immediately on this, because the expanded HUD needs a larger overhaul on its own, I will fix it then.

**Comment by avichou** [comment]
> That does indeed make more sense! I understand why you'd want that. I won't work immediately on this, because the expanded HUD needs a larger overhaul on its own, I will fix it then.

thank you !! sure no problem :)) thanks man
