### ISSUE TITLE
[Feature] Two Finger Swipe Reverse Direction

### ISSUE THREAD

**Issue by Awesomeplayer165** [Wouter01/MediaMate-Releases#45]
Is there a way to reverse the swipe for two finger SystemHUD > iOS control. Right now, my two fingers move left on the trackpad to increase (or go right), which doesn't make intuitive sense. Is there a way to reverse this or use the System's trackpad direction (mine is reversed) for this. Thanks!

**Comment by Wouter01** [comment]
Thank you for the bug report. MediaMate will respect the trackpad natural scrolling settings in the next update.

**Comment by Wouter01** [comment]
A new update has been released which should fix the issue. A new toggle has been added in the "Advanced" settings to reverse the swipe direction. Could you check and, if fixed, close the issue?

**Comment by Awesomeplayer165** [comment]
Yes works thanks!
