### ISSUE TITLE
Feature Request: Cool animation when notch doesn't have anything to do (Not in Now playing mode)

### ISSUE THREAD

**Issue by Bhanu1776** [Wouter01/MediaMate-Releases#48]
Default:

https://github.com/Wouter01/MediaMate-Releases/assets/53951343/54af2c27-0abc-43ec-b7b6-4be30e46f9d5

Requested:

https://github.com/Wouter01/MediaMate-Releases/assets/53951343/e65d3189-530a-4c4c-81ce-c92fffab846b

**Comment by Wouter01** [comment]
Thank you for the feature request. I feel like this would be mostly distracting, hence why I'm not planning to add it.

**Comment by Bhanu1776** [comment]
Thank you for considering my feature request. I completely understand your concern about potential distractions. However, I believe that adding an animation for when the notch doesn't have anything to display, with the option to enable or disable it, could provide users with a more customizable experience.

By making it an optional feature, users who prefer a minimalist interface can choose to keep it disabled, while those who enjoy added visual flair can opt to enable it. 

Thank you for your consideration.

**Comment by Wouter01** [comment]
I understand your thoughts completely! I'd love to make it happen some day, however I have to make some choices about what is worth it and what isn't. If I did add each feature request, the app would have at least double the options it has now. Each added option adds an extra parameter I have to test when making changes, and an extra possibility to add bugs. Hence why I'm hesitant

**Comment by Bhanu1776** [comment]
Absolutely, your concerns are completely valid. Prioritizing features and carefully considering the trade-offs is essential for maintaining a stable and manageable application. 
Keep up the great work of making thoughtful decisions for your application's development!
