### ISSUE TITLE
Spacing in settings

### ISSUE THREAD

**Issue by flexwie** [Wouter01/MediaMate-Releases#5]
**Describe the bug**
Not really a bug, more of a visual thing. The spacing in the settings is a bit off sometimes.

**To Reproduce**
1. Open preferences
2. Go to 'Now Playing'

**Screenshots**
![image](https://user-images.githubusercontent.com/1215778/183358725-67b2e611-a5f5-4fd2-8103-01fb88b87465.png)

**Comment by Wouter01** [comment]
I see! Going to have a look at it. In Ventura, the settings look much cleaner atm. Monterey still uses the old style which I had not really looked after.
