### ISSUE TITLE
Feature request: Cool animation when idle

### ISSUE THREAD

**Issue by Bhanu1776** [Wouter01/MediaMate-Releases#51]
Is it possible to add an animation when there's no now-playing feature activated(Idle) ??

Before:

https://github.com/Wouter01/MediaMate-Releases/assets/53951343/39146981-3a45-4668-a52c-ad6e7d857441

After:

https://github.com/Wouter01/MediaMate-Releases/assets/53951343/43ba1d3a-6ae5-4362-bedc-93f748dedf72

**Comment by Wouter01** [comment]
Hi,

I have already answered your question [here](https://github.com/Wouter01/MediaMate-Releases/issues/48)

**Comment by Bhanu1776** [comment]
So sorry, I thought it was deleted for some reason
