### ISSUE TITLE
macOS 14.4 Seems to have broken the Brightness UI

### ISSUE THREAD

**Issue by Ender-Wang** [Wouter01/MediaMate-Releases#52]
**Describe the bug**
After upgrading to macOS 14.4, brightness changes doesnot have any UI hints, Classic, iOS, Circular, Notch Beta, all doesnot work with brightness changes.
MacBook Pro 14 M3 Max, macOS 14.4 23E214.

**Comment by Wouter01** [comment]
Which event controller mode are you using?

**Comment by Ender-Wang** [comment]
Keyboard mode: showing system brightness UI, System mode & BetterDisplay mode: nothing, not even the system UI.

**Comment by Ender-Wang** [comment]
BetterDisplay at ver 2.2.5.

**Comment by Wouter01** [comment]
So I'm assuming you're using the BetterDisplay event controller mode.
In that case, could you make sure:
- BetterDisplay PRO is activated
- Check that the options described in the event controller mode settings are enabled in the BetterDisplay app
- Quit and restart both apps

**Comment by Ender-Wang** [comment]
Yes, Pro is active and, event controller mode is BetterDisplay and there a green bubble says BetterDisplay is running, and quite both, start BD first, then MM, or the other way around, still the same issue with brightness UI that nothing shows up. Volume and NowPlaying is working fine tho.

**Comment by Wouter01** [comment]
Have you checked that these options are set correctly?

<img width="463" alt="image" src="https://github.com/Wouter01/MediaMate-Releases/assets/62355975/952cc5e7-e007-4110-9e3a-02ea675d6662">

**Comment by Ender-Wang** [comment]
Are those settings supposed to be in the state shown in your screenshot? (I typically leave them default, I did not change anything before macOS 14.4 when everything works.)

**Comment by Wouter01** [comment]
Yes. MediaMate should change them automatically, but something might went wrong.

**Comment by Ender-Wang** [comment]
I just changed them to those On, off, off state, and restarted both apps, still not working.

**Comment by Wouter01** [comment]
Does BetterDisplay work correctly when MediaMate is disabled? You can try this by setting the event controller to "Keyboard" (which will revert the BetterDisplay settings) and afterwards quitting MediaMate

**Comment by Ender-Wang** [comment]
Just to let you know, I changed BD to ver 2.2.2 via clean install, which is the version I was on before macOS 14.4 when everything works, still have the exact same issue as BD on 2.2.5.

**Comment by Ender-Wang** [comment]
> Does BetterDisplay work correctly when MediaMate is disabled? You can try this by setting the event controller to "Keyboard" (which will revert the BetterDisplay settings) and afterwards quitting MediaMate

Yes, it works with MM completely off or set to KeyBoard mode. I mean BD is working even when MM set to BetterDisplay mode, but just the brightness UI is not showing up while Volume UI is working. Maybe in macOS 14.4 Apple changes something related to brightness control UI. If you have a mac with 14.4, you can try it.

**Comment by Ender-Wang** [comment]
Just found another thing that, I usually have this settings on on BD: XDR/HDR Upscaling, Software Dimming->Show extra OSD icon if keyboard adjustment causes upscaling or extra dimming, and I just see the indicator, but only the indicator, system UI is gone. (MM set to BD mode.)
![CleanShot_2024-03-08_13-52-12](https://github.com/Wouter01/MediaMate-Releases/assets/33310255/04ffb955-7cfe-4258-9a4a-c8c3bc1d94ff)

**Comment by Ender-Wang** [comment]
Just tried the four different styles, same situation as I said above: I can see only the indicator, no system UI, no MM UI(all four styles), when MM set to BD mode.

**Comment by Wouter01** [comment]
macOS 14.4 should not change anything. I have already checked and it is working fine on my side using 14.4 and 2.25, so the problem must lie somewhere else. Have you already tried restarting your mac?

As for the green arrow, this happens because MediaMate still needs to block the native HUD while in the BetterDisplay event controller mode. This is needed because natively support audio devices are not managed by BetterDisplay. You might be able to solve this by disabling "Sync" and setting the event controller mode for audio to "Keyboard", and for brightness to "BetterDisplay". This will still not resolve your original problem though.

**Comment by Ender-Wang** [comment]
Still not working. I have tried with BD off, just use MM, still the same issue😅

**Comment by Ender-Wang** [comment]
Okak, I think I found out the resaon LMAO, I jsut saw the brightness icon here is grayed out, I do not remember somehow I clicked it, I do not know it's even clickable until then LMAO
![CleanShot_2024-03-08_14-13-06](https://github.com/Wouter01/MediaMate-Releases/assets/33310255/2d6e767f-3804-4b78-a2bd-b98cf130b068)

**Comment by Wouter01** [comment]
Glad it’s working now! This is useful feedback.
