### ISSUE TITLE
feature:  hope to access a payment method supported by the Chinese mainland, such as Alipay.

### ISSUE THREAD

**Issue by Fengjing95** [Wouter01/MediaMate-Releases#57]
Most Chinese people, like me, do not have a credit card that supports Global Payment, so they need to access some payment methods available in the mainland.

**Comment by Wouter01** [comment]
I am limited to what Gumroad offers for payment methods. I recommend sending feedback to Gumroad regarding this issue.  (Tax is handled through Gumroad, which is why I cannot offer a payment method outside of it)
