### ISSUE TITLE
Mute not working using a docking station

### ISSUE THREAD

**Issue by flexwie** [Wouter01/MediaMate-Releases#6]
**Describe the bug**
I have my MacBook docked into a USB-C docking station at my desk. That station is connected to my desktop speakers. The disables volume control in vanilla MacOS, but so far I could still mute/unmute the speakers with the appropriate key on my keyboard and it would show the correct icon. In MediaMate, I can still mute/unmute but it will always show the audio as muted in the HUD.

**To Reproduce**
1. Mute/Unmute audio with docking station.

**Expected behavior**
The icon in the HUD toggles from muted to unmuted and back.

**Please complete the following information:**
 - OS: Monterey 12.4
 - Device: MBP 14" M1 Pro 2021
 - Version: [v1.0-59](https://github.com/Wouter01/MediaMate-Releases/releases/tag/v1.0_59) (I hope)

**In case of a keyboard-related issue, please specify the used keyboard**:
- Layout: QUERTZ
- Internal/External Logitech MX Keys for Mac
- non-touchbar

**Additional context**
Lenovo USB-C docking station with Bose companion series 2 III speakers

**Comment by Wouter01** [comment]
That's weird! Few extra questions:
Does it work without the docking station? And is the docking station part of a monitor, or is it a separate device?

**Comment by flexwie** [comment]
The speakers are plugged into the docking station and the station is not part of my monitor.
