### ISSUE TITLE
After my mac goes to sleep the brightess effect is not working anymore

### ISSUE THREAD

**Issue by teodoradriann** [Wouter01/MediaMate-Releases#61]
**Describe the bug**
I have my event mode on keyboard and after my Mac goes to sleep the brightness bar is set to the default one. The keyboard brightness and volume work as intended tho. If i set my event to macOS it works and there is no problem.

**Please complete the following information:**
 - OS: [Sonoma 14.5]
 - Device [e.g. M2 Max MacBook Pro]
 - Version [e.g. 3.3.0 build 269]

**Comment by Wouter01** [comment]
Hi,

Are you using any apps that could interfere with MediaMate?

**Comment by teodoradriann** [comment]
> Hi,
> 
> 
> 
> Are you using any apps that could interfere with MediaMate?

Not that I know of. Only BetterDisplay

**Comment by Wouter01** [comment]
> > Hi,
> > Are you using any apps that could interfere with MediaMate?
> 
> Not that I know of. Only BetterDisplay

Are you using the BetterDisplay event controller mode? (MediaMate settings -> general -> event controller mode)

**Comment by teodoradriann** [comment]
> > > Hi,
> 
> > > Are you using any apps that could interfere with MediaMate?
> 
> > 
> 
> > Not that I know of. Only BetterDisplay
> 
> 
> 
> Are you using the BetterDisplay event controller mode? (MediaMate settings -> general -> event controller mode)

No, im using keyboard event and it doesnt work. If i switch to macos event it works all the time and if i switch to BetterDisplay it doesnt work at all, it never shows the new UI neither the classic one.

**Comment by Wouter01** [comment]
Using MediaMate and BetterDisplay simultaneously will not work well unless the BetterDisplay integration is used. Are you on BetterDisplay 2.2.0 or higher, and do you have Pro mode enabled?

**Comment by teodoradriann** [comment]
I am on 2.3.4 and I don't have Pro mode. Yea I wanted to use BD integration but when i select it as i said it just doesnt work at all anymore, not even showing the classic hud. Do i need to buy the Pro version in order to make it work?

**Comment by Wouter01** [comment]
Yes, Pro mode is required (this should be stated in the description of the setting). If you prefer to not purchase BetterDisplay Pro, best thing I can suggest is to use the "system" mode, as both apps will not interfere with each other in this mode. Note that this will not work perfectly. For example, XDR brightness won't be shown in the MediaMate interface. For full compatibility, the BetterDisplay event mode is required

**Comment by teodoradriann** [comment]
ok thank you
