### ISSUE TITLE
add rewind and skip 15 seconds buttons with notch style 

### ISSUE THREAD

**Issue by avichou** [Wouter01/MediaMate-Releases#64]
pretty self explanatory, would be nice to have the rewind and skip buttons with the notch style as well

ps: it would be handy if it were avaiable by defaut, without having to click twice. having the controls via a simple click on mediamate menu bar icon

**Comment by Wouter01** [comment]
Thank you for the suggestion. I will add them in a future update

**Comment by avichou** [comment]
> Thank you for the suggestion. I will add them in a future update

thank you for being so quick and effective and listening and also yeah your app is amazing :)

**Comment by avichou** [comment]
> Thank you for the suggestion. I will add them in a future update

do you think it'd be possible to add it directly in the interface, reachable with a single click ? unlike classis menu (rounded) which requires double clicking 

basically making it available right here, next or below those buttons 


<img width="521" alt="Capture d’écran 2024-06-15 à 16 32 14" src="https://github.com/Wouter01/MediaMate-Releases/assets/86660671/78c077cb-d6c1-4ffc-be4c-0de3ea83dba8">

**Comment by Wouter01** [comment]
That's the goal, yes.
