### ISSUE TITLE
clicking on the icon doesn't bring the app upfront

### ISSUE THREAD

**Issue by avichou** [Wouter01/MediaMate-Releases#66]
i'm not sure it can be fixed 

youtube music via chrome and safari are fucked (extremely slow) . steve88k version is also half broken 

i have settled on this very popular app https://github.com/th-ch/youtube-music

controls work just fine, however clicking on the thumbnail doesnt take me to the app /doesnt bring it to front

https://github.com/Wouter01/MediaMate-Releases/assets/86660671/1dcd5018-4236-4e4e-979d-0619c53e1e39

do you think you could do something about it perhaps ? or is it impossible due to the nature of third party apps. idk what fw they use

**Comment by Wouter01** [comment]
This happens because this app does not report a part of its status correctly. However, I have looked into it and am able to work around this. The next update will fix this.

**Comment by avichou** [comment]
You're amazing

Le sam. 15 juin 2024, 16:57, Wouter Hennen ***@***.***> a
écrit :

**Comment by avichou** [comment]
> This happens because this app does not report a part of its status correctly. However, I have looked into it and am able to work around this. The next update will fix this.

you are amazing, tysm

**Comment by Wouter01** [comment]
Version 3.5.0 has been released, which should fix this issue.
