### ISSUE TITLE
Notch media playing not working anymore

### ISSUE THREAD

**Issue by teodoradriann** [Wouter01/MediaMate-Releases#67]
After the update to 3.4.2 when i play media it wont show in the notch anymore. Tried to restart the app and computer, not working.

**Comment by teodoradriann** [comment]
<img width="1241" alt="image" src="https://github.com/Wouter01/MediaMate-Releases/assets/78275594/31fdc756-9aff-4a32-9ac2-44b14fda49a4">

**Comment by Wouter01** [comment]
Hi,

The new version should not change the behavior of the Now Playing feature. Could you verify:
- MediaMate Now Playing settings are configured correctly (The "reveal when" and "allowed apps" settings)
- if it works in 3.3.0 (https://github.com/Wouter01/MediaMate-Releases/releases/download/v3.3.0_269/MediaMate.dmg)

If both options not work, could you tell me which app you're using to play music, and send a log? (MediaMate settings -> about -> send feedback)

**Comment by teodoradriann** [comment]
<img width="1020" alt="image" src="https://github.com/Wouter01/MediaMate-Releases/assets/78275594/91012ef7-c650-4c45-8062-cc16cb54b69f">
<img width="1020" alt="image" src="https://github.com/Wouter01/MediaMate-Releases/assets/78275594/ae1ca186-b518-44c9-b523-c3bf7134b878">
i'm using spotify. before the update it worked with no problems

**Comment by teodoradriann** [comment]
i just sent the feedback

**Comment by teodoradriann** [comment]
On version 3.3.0 the now playing feature is working.

**Comment by Wouter01** [comment]
Hi,

It looks like one of your configuration settings is misconfigured. In Allowed Apps, could you change "Show" to "Hide"?

**Comment by teodoradriann** [comment]
Thank you yea in 3.3.0 it worked even if it was set on Show now i've changed it and updated to the newest version and it works.
