### ISSUE TITLE
App refuses to open

### ISSUE THREAD

**Issue by Mcrich23** [Wouter01/MediaMate-Releases#69]
**Describe the bug**
Downloaded update and app refuses to open now

**To Reproduce**
1. Try to open app

**Expected behavior**
The app should open in the toolbar

**Please complete the following information:**
 - OS: Sonoma 14.5
 - Device M1 Pro MacBook Pro
 - Version 3.5 Release

**Comment by Mcrich23** [comment]
Update: it's fixed, I just had to try opening it from finder because of a downloaded from internet warning. Can this please be fixed in the future?

**Comment by Wouter01** [comment]
Hi,

macOS will show a warning when opening notarized apps for the first time. This is expected behaviour. It should now be shown again after updating the app.
