### ISSUE TITLE
Menu items unavailable when no menubar icon is displayed and running MM app

### ISSUE THREAD

**Issue by andraz-kozelj** [Wouter01/MediaMate-Releases#7]
**Describe the bug**
Menu items do not respond to clicks (as if the window is a modal top level window). 

**To Reproduce**
Run MM, in Settings un-check "Show Menubar Icon", close the app.
In order to reach settings, you need to run MM again. If you want to click the menus, they do not respond.

ON THE OTHER HAND
If you have a menubar icon, click on it, click Settings, menu items are normally accessible.

**Expected behavior**
When Settings window is displyed, MM menu items should be accessible.

**Please complete the following information:**
 - OS: macOS 13 Ventura beta 5
 - Device M1 Macbook Pro 16"
 - Version 1.1

**Comment by Wouter01** [comment]
Thanks for submitting the bug! It was weird, but it's fixed now. Will be added in the next update :)
