### ISSUE TITLE
MediaMate crashes silently at random

### ISSUE THREAD

**Issue by andylundqvist** [Wouter01/MediaMate-Releases#70]
MediaMate crashes (silently, meaning I get no "crash report" popup) for me and needs to be relaunched manually.

I use Lunar and this happens both if I use the standard "Keyboard" or "Lunar" event mode in MediaMate. I have tested Lunar in both DDC mode and software mode, it makes no difference.

MediaMate works as expected as long as it runs, but appears to randomly crash. I do not know exactly when, it may be when the screen is locked or going into screensaver mode.

Accessibility Permission has been granted.

I have tried with both Apple Wireless Keyboard (small version) and Logitech MX Keys, the brightness controls work but it does not make any difference regarding the crashing.

I have an external monitor connected via usb-c (I don't know if this is relevant).

Please let me know if you need any other details or if I can find any post any crash logs.

I have not used any version prior to 3.5.0 build 278 (I just bought MediaMate) so I can't compare anything.

 - OS: macOS 14.5 Sonoma
 - Device: M1 Macbook Air 2020, 8 GB
 - MediaMate version: 3.5.0 build 278 
 - Lunar version: 6.7.13

**Comment by andylundqvist** [comment]
I should add: It does not appear to matter which style I use, it happens both with Notch and iOS. Transition style also does not seem to matter.

**Comment by Wouter01** [comment]
Thank you for the extensive bug report! I am looking into the issue, it seems related to the Lunar compatibility mode.
I might have found a potential fix for the issue, and was wondering if you could test a new version of the app? If you still experience issues (or not), let me know. Thank you!

[MediaMate.zip](https://github.com/user-attachments/files/15932626/MediaMate.zip)

**Comment by andylundqvist** [comment]
Thank you @Wouter01! I have installed it and will let it run for a few days and then let you know.

**Comment by andylundqvist** [comment]
After quite a lot of testing I have not had the problem anymore so the fix you made seems to work, @Wouter01. Thank you!

**Comment by andylundqvist** [comment]
Version 3.5.1 build 279 seems to have fixed it. 🙌

**Comment by Wouter01** [comment]
This version has now been released. The build is the same as the one shared here, so updating isn't necessary. Thank you for confirming it works now!
