### ISSUE TITLE
Now Playing not displaying/working

### ISSUE THREAD

**Issue by orangjuce01** [Wouter01/MediaMate-Releases#75]
**Describe the bug**
The now playing for the notch is not recognizing that something is playing, apple music, youtube, etc. despite macOS being able to show that something is indeed playing media. I've already tried restarting, closing and reopening the app, reinstalling but it still won't work. Other features do work, only now playing is being weird.

It worked just fine yesterday but when I tried testing with the allowed apps, it suddenly won't work so I suspect my tinkering messed something up?

<img width="1069" alt="Screenshot 2024-08-27 at 8 28 19 AM" src="https://github.com/user-attachments/assets/07054db8-b563-48f8-8388-fba3cf45f9fe">

 - OS: Sonoma 14.6.1
 - Device: M2 Macbook Air
 - Version 3.5.1 build 279

**Comment by Wouter01** [comment]
Hi,

Is this still an issue? Apologies for the late reply, I looked over this issue.

What's likely happening is that you have set the allowed apps setting to **Show** the Now Playing HUD for an empty list -> Nothing will be shown. Setting it to **Hide** the Now Playing HUD for an empty list should fix the issue.

**Comment by orangjuce01** [comment]
Hi, your suggestion worked and it now works fine. Thanks!
