### ISSUE TITLE
MediaMate Crashes on Launch

### ISSUE THREAD

**Issue by Bawnorton** [Wouter01/MediaMate-Releases#78]
**Describe the bug**
When opening MediaMate nothing happens, upon looking into diagnostic reports, it is because it has been crashing immediately

**To Reproduce**
1. Download MediaMate
2. Install Application
3. Launch Application

**Expected behavior**
Application Launches

**Please complete the following information:**
 - OS: Sonoma 15.0 Beta
 - Device: Macbook M1 Pro
 - Version: 3.6.1
 
Crash report:
[MediaMate-2024-09-20-105746.ips.zip](https://github.com/user-attachments/files/17079015/MediaMate-2024-09-20-105746.ips.zip)

**Comment by Bawnorton** [comment]
No longer reproducible after moving off the MacOS Beta branch

**Comment by Wouter01** [comment]
Great!
