### ISSUE TITLE
An 'x' sometimes appear on hover on the Now Playing HUD

### ISSUE THREAD

**Issue by pads1** [Wouter01/MediaMate-Releases#9]
**Describe the bug**
An 'x' sometimes appear on hover on the Now Playing HUD

**To Reproduce**
1. Play any song from Spotify or Apple Music.
2. Hover over the Now Playing HUD, and an 'x' should appear over the album artwork.

**Expected behavior**
The 'x' should not be present there, unless it is dedicated for a much needed function (i.e. using the 'x' to close the app from the HUD)

**Screenshots**
<img width="145" alt="Screenshot 2022-08-11 at 2 31 57 PM" src="https://user-images.githubusercontent.com/23331269/184076516-3fb9952b-0db9-460c-9023-a2169e685d2c.png">

**Please complete the following information:**
 - OS: Ventura 13.0 beta
 - Device: M1 MacBook Pro
 - Version: 1.1

**Comment by Wouter01** [comment]
Thanks for the bug report!
The "x" pops up when the user hovers over the HUD. This is so the user can quickly dismiss the HUD if it is in the way. However, there are currently some issues where the hovering is not always detected correctly.
However, I'm planning to move the x to the edge of the window, kind of like how notifications work. This will make the intent of it probably more clear

**Comment by Wouter01** [comment]
This has been fixed in v1.2.1
